#%RAML 0.8
title: Configurations
version: v1
baseUri: http://github.com/org/folio/lsp-apis
protocols: [ HTTPS ]

documentation:
  - title: Configuration API updating system wide configurations
    content: <b>This documents the API calls that can be made to update configurations in the system</b>


schemas:
  - configs: !include ../_schemas/kv_configurations.schema
  - config: !include ../_schemas/kv_configuration.schema
  - libraries: !include ../_schemas/library.schema
  - audits: !include ../_schemas/audits.schema
  - audit: !include ../_schemas/audit.schema

traits:
  - secured: !include ../../raml-util/traits/auth.raml
  - orderable: !include ../../raml-util/traits/orderable.raml
  - pageable:  !include ../../raml-util/traits/pageable.raml
  - searchable: !include ../../raml-util/traits/searchable.raml
  - language: !include ../../raml-util/traits/language.raml

resourceTypes:
  - collection: !include ../../raml-util/rtypes/collection.raml
  - collection-item: !include ../../raml-util/rtypes/item-collection.raml
  - get-only: !include ../../raml-util/rtypes/get-only.raml

/configurations:
  /entries:
    displayName: Configurations
    description: <ul><li>Retrieve configurations for all modules associated with a specific institution.</li><li>Add a module to the configuration tables</li></ul><br>The JWT token limits the returned configurations to those of the calling institution
    type:
      collection:
        schemaCollection: configs
        schemaItem: config
        exampleCollection: !include ../_examples/kv_configuration.sample
        exampleItem: !include ../_examples/kv_configuration.sample
    get:
      is: [
        searchable: {description: "with valid searchable fields: for example module = CIRCULATION", example: "scope.institution_id=aaa"},
        orderable: {fieldsList: "module"},
        pageable
      ]
    /{entryId}:
      displayName: Module configurations
      description: <ul><li>Delete or Update a specific module from the configuration table<br>An example of this would be to add a configuration to the circulation table or to delete a configuration from the circulation table. The query parameters can be used to filter for the desired module's configuration</li><li>Get a specified module's configurations</li></ul><br>The JWT token limits the returned configurations to those of the calling institution
      type:
        collection-item:
          schema: configs
          exampleItem: !include ../_examples/kv_configuration.sample
      get:
        is: [
          searchable: {description: "with valid searchable fields: for example name = renewals_allowed_count", example: "scope.institution_id=aaa"},
          orderable: {fieldsList: "module"},
          pageable
        ]
  /audit:
    displayName: Audit Configurations
    description: Retrieve entries from the audit configuration table.
    type:
      get-only:
        schema: audits
        exampleCollection: ../_examples/audit.sample
    get:
      is: [
        searchable: {description: "with valid searchable fields: for example module = CIRCULATION", example: "scope.institution_id=aaa"},
        orderable: {fieldsList: "module"},
        pageable
      ]
