package com.sample

import org.folio.rest.jaxrs.model.Patron;


rule "Patron needs one ID at the least"

	no-loop

    when
        p : Patron( patronBarcode  == null, patronLocalId == null )
    then
    	throw new java.lang.Exception("Patron needs one ID field populated at the least");
        //System.out.println( "aaaaaaaaa" );
        //p.setPatronName("Joe Shmoe");
        //update( p );
end

rule "Patron Name null"
    when
        Patron( patronName  == null, myMessage : patronLocalId )
    then
        System.out.println("---------------------- name is null for id = " + myMessage  );
end
